// Generated by CoffeeScript 1.7.1
(function() {
  var image, vmath;

  image = {};

  if (typeof window !== "undefined" && window !== null) {
    window.image = image;
  }

  if ((typeof module !== "undefined" && module !== null ? module.exports : void 0) != null) {
    module.exports = image;
  }

  vmath = window.vmath;

  image.image3f = (function() {
    image3f._w = 0;

    image3f._h = 0;

    image3f._d = null;

    function image3f(_w, _h, v) {
      var i;
      this._w = _w != null ? _w : 0;
      this._h = _h != null ? _h : 0;
      if (v == null) {
        v = null;
      }
      this._d = (function() {
        var _i, _ref, _results;
        _results = [];
        for (i = _i = 0, _ref = this._w * this._h; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
          _results.push(new vmath.vec3f(v != null ? v.array() : void 0));
        }
        return _results;
      }).call(this);
    }

    image3f.prototype.wwidth = function() {
      return this._w;
    };

    image3f.prototype.hheight = function() {
      return this._h;
    };

    image3f.prototype.at = function(i, j) {
      return this._d[j * this._w + i];
    };

    image3f.prototype.set_at = function(i, j, v) {
      return this._d[j * this._w + i] = v.clone();
    };

    image3f.prototype.data = function() {
      return this._d;
    };

    image3f.prototype.flipy = function() {
      var i, j, ret, _i, _j, _ref, _ref1;
      ret = new image.image3f(this.wwidth(), this.hheight());
      for (j = _i = 0, _ref = this.hheight(); 0 <= _ref ? _i < _ref : _i > _ref; j = 0 <= _ref ? ++_i : --_i) {
        for (i = _j = 0, _ref1 = this.wwidth(); 0 <= _ref1 ? _j < _ref1 : _j > _ref1; i = 0 <= _ref1 ? ++_j : --_j) {
          ret._d[(this.hheight() - 1 - j) * this.wwidth() + i] = (this.at(i, j)).clone();
        }
      }
      return ret;
    };

    image3f.prototype.gamma = function(g) {
      var i, j, ret, _i, _j, _ref, _ref1;
      ret = new image.image3f({
        w: this.wwidth(),
        h: this.hheight()
      });
      for (j = _i = 0, _ref = this.hheight(); 0 <= _ref ? _i < _ref : _i > _ref; j = 0 <= _ref ? ++_i : --_i) {
        for (i = _j = 0, _ref1 = this.wwidth(); 0 <= _ref1 ? _j < _ref1 : _j > _ref1; i = 0 <= _ref1 ? ++_j : --_j) {
          ret._d[j * this._w + i] = (vmath.pow(this._d[j * this._w + i], g)).clone();
        }
      }
      return ret;
    };

    image3f.prototype.scale = function(s) {
      var i, j, ret, _i, _j, _ref, _ref1;
      ret = new image.image3f({
        w: this.wwidth(),
        h: this.hheight()
      });
      for (j = _i = 0, _ref = this.hheight(); 0 <= _ref ? _i < _ref : _i > _ref; j = 0 <= _ref ? ++_i : --_i) {
        for (i = _j = 0, _ref1 = this.wwidth(); 0 <= _ref1 ? _j < _ref1 : _j > _ref1; i = 0 <= _ref1 ? ++_j : --_j) {
          ret._d[j * this._w + i] = (vmath.mul(this._d[j * this._w + i], s)).clone();
        }
      }
      return ret;
    };

    return image3f;

  })();

}).call(this);

//# sourceMappingURL=image.map
