// Generated by CoffeeScript 1.7.1
(function() {
  var json;

  json = {};

  if (typeof window !== "undefined" && window !== null) {
    window.json = json;
  }

  if ((typeof module !== "undefined" && module !== null ? module.exports : void 0) != null) {
    module.exports = json;
  }

  json.load_json = function(filename) {
    var obj;
    $.ajaxSetup({
      async: false
    });
    obj = null;
    $.getJSON(filename, function(data) {
      return obj = data;
    });
    return obj;
  };

}).call(this);

//# sourceMappingURL=json.map
